package org.rubby;
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cdr.pro

public final class CdrPro {
  private CdrPro() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface SmCdrOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required string oaddr = 1;
    boolean hasOaddr();
    String getOaddr();
    
    // required string oareacode = 2;
    boolean hasOareacode();
    String getOareacode();
    
    // required string daddr = 3;
    boolean hasDaddr();
    String getDaddr();
    
    // required string dareacode = 4;
    boolean hasDareacode();
    String getDareacode();
    
    // required string timestamp = 5;
    boolean hasTimestamp();
    String getTimestamp();
    
    // required string type = 6;
    boolean hasType();
    String getType();
  }
  public static final class SmCdr extends
      com.google.protobuf.GeneratedMessage
      implements SmCdrOrBuilder {
    // Use SmCdr.newBuilder() to construct.
    private SmCdr(Builder builder) {
      super(builder);
    }
    private SmCdr(boolean noInit) {}
    
    private static final SmCdr defaultInstance;
    public static SmCdr getDefaultInstance() {
      return defaultInstance;
    }
    
    public SmCdr getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return CdrPro.internal_static_SmCdr_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return CdrPro.internal_static_SmCdr_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required string oaddr = 1;
    public static final int OADDR_FIELD_NUMBER = 1;
    private java.lang.Object oaddr_;
    public boolean hasOaddr() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getOaddr() {
      java.lang.Object ref = oaddr_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          oaddr_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getOaddrBytes() {
      java.lang.Object ref = oaddr_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        oaddr_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required string oareacode = 2;
    public static final int OAREACODE_FIELD_NUMBER = 2;
    private java.lang.Object oareacode_;
    public boolean hasOareacode() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getOareacode() {
      java.lang.Object ref = oareacode_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          oareacode_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getOareacodeBytes() {
      java.lang.Object ref = oareacode_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        oareacode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required string daddr = 3;
    public static final int DADDR_FIELD_NUMBER = 3;
    private java.lang.Object daddr_;
    public boolean hasDaddr() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public String getDaddr() {
      java.lang.Object ref = daddr_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          daddr_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getDaddrBytes() {
      java.lang.Object ref = daddr_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        daddr_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required string dareacode = 4;
    public static final int DAREACODE_FIELD_NUMBER = 4;
    private java.lang.Object dareacode_;
    public boolean hasDareacode() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public String getDareacode() {
      java.lang.Object ref = dareacode_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          dareacode_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getDareacodeBytes() {
      java.lang.Object ref = dareacode_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        dareacode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required string timestamp = 5;
    public static final int TIMESTAMP_FIELD_NUMBER = 5;
    private java.lang.Object timestamp_;
    public boolean hasTimestamp() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    public String getTimestamp() {
      java.lang.Object ref = timestamp_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          timestamp_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getTimestampBytes() {
      java.lang.Object ref = timestamp_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        timestamp_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required string type = 6;
    public static final int TYPE_FIELD_NUMBER = 6;
    private java.lang.Object type_;
    public boolean hasType() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    public String getType() {
      java.lang.Object ref = type_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          type_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getTypeBytes() {
      java.lang.Object ref = type_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        type_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    private void initFields() {
      oaddr_ = "";
      oareacode_ = "";
      daddr_ = "";
      dareacode_ = "";
      timestamp_ = "";
      type_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasOaddr()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasOareacode()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasDaddr()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasDareacode()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTimestamp()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getOaddrBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getOareacodeBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getDaddrBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getDareacodeBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, getTimestampBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBytes(6, getTypeBytes());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getOaddrBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getOareacodeBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getDaddrBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getDareacodeBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getTimestampBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, getTypeBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static CdrPro.SmCdr parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static CdrPro.SmCdr parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static CdrPro.SmCdr parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static CdrPro.SmCdr parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static CdrPro.SmCdr parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static CdrPro.SmCdr parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static CdrPro.SmCdr parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static CdrPro.SmCdr parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static CdrPro.SmCdr parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static CdrPro.SmCdr parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(CdrPro.SmCdr prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements CdrPro.SmCdrOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return CdrPro.internal_static_SmCdr_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return CdrPro.internal_static_SmCdr_fieldAccessorTable;
      }
      
      // Construct using CdrPro.SmCdr.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        oaddr_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        oareacode_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        daddr_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        dareacode_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        timestamp_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        type_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return CdrPro.SmCdr.getDescriptor();
      }
      
      public CdrPro.SmCdr getDefaultInstanceForType() {
        return CdrPro.SmCdr.getDefaultInstance();
      }
      
      public CdrPro.SmCdr build() {
        CdrPro.SmCdr result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private CdrPro.SmCdr buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        CdrPro.SmCdr result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public CdrPro.SmCdr buildPartial() {
        CdrPro.SmCdr result = new CdrPro.SmCdr(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.oaddr_ = oaddr_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.oareacode_ = oareacode_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.daddr_ = daddr_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.dareacode_ = dareacode_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.timestamp_ = timestamp_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.type_ = type_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof CdrPro.SmCdr) {
          return mergeFrom((CdrPro.SmCdr)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(CdrPro.SmCdr other) {
        if (other == CdrPro.SmCdr.getDefaultInstance()) return this;
        if (other.hasOaddr()) {
          setOaddr(other.getOaddr());
        }
        if (other.hasOareacode()) {
          setOareacode(other.getOareacode());
        }
        if (other.hasDaddr()) {
          setDaddr(other.getDaddr());
        }
        if (other.hasDareacode()) {
          setDareacode(other.getDareacode());
        }
        if (other.hasTimestamp()) {
          setTimestamp(other.getTimestamp());
        }
        if (other.hasType()) {
          setType(other.getType());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasOaddr()) {
          
          return false;
        }
        if (!hasOareacode()) {
          
          return false;
        }
        if (!hasDaddr()) {
          
          return false;
        }
        if (!hasDareacode()) {
          
          return false;
        }
        if (!hasTimestamp()) {
          
          return false;
        }
        if (!hasType()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              oaddr_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              oareacode_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              daddr_ = input.readBytes();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              dareacode_ = input.readBytes();
              break;
            }
            case 42: {
              bitField0_ |= 0x00000010;
              timestamp_ = input.readBytes();
              break;
            }
            case 50: {
              bitField0_ |= 0x00000020;
              type_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required string oaddr = 1;
      private java.lang.Object oaddr_ = "";
      public boolean hasOaddr() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getOaddr() {
        java.lang.Object ref = oaddr_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          oaddr_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setOaddr(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        oaddr_ = value;
        onChanged();
        return this;
      }
      public Builder clearOaddr() {
        bitField0_ = (bitField0_ & ~0x00000001);
        oaddr_ = getDefaultInstance().getOaddr();
        onChanged();
        return this;
      }
      void setOaddr(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        oaddr_ = value;
        onChanged();
      }
      
      // required string oareacode = 2;
      private java.lang.Object oareacode_ = "";
      public boolean hasOareacode() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getOareacode() {
        java.lang.Object ref = oareacode_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          oareacode_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setOareacode(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        oareacode_ = value;
        onChanged();
        return this;
      }
      public Builder clearOareacode() {
        bitField0_ = (bitField0_ & ~0x00000002);
        oareacode_ = getDefaultInstance().getOareacode();
        onChanged();
        return this;
      }
      void setOareacode(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        oareacode_ = value;
        onChanged();
      }
      
      // required string daddr = 3;
      private java.lang.Object daddr_ = "";
      public boolean hasDaddr() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public String getDaddr() {
        java.lang.Object ref = daddr_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          daddr_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setDaddr(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        daddr_ = value;
        onChanged();
        return this;
      }
      public Builder clearDaddr() {
        bitField0_ = (bitField0_ & ~0x00000004);
        daddr_ = getDefaultInstance().getDaddr();
        onChanged();
        return this;
      }
      void setDaddr(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000004;
        daddr_ = value;
        onChanged();
      }
      
      // required string dareacode = 4;
      private java.lang.Object dareacode_ = "";
      public boolean hasDareacode() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public String getDareacode() {
        java.lang.Object ref = dareacode_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          dareacode_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setDareacode(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        dareacode_ = value;
        onChanged();
        return this;
      }
      public Builder clearDareacode() {
        bitField0_ = (bitField0_ & ~0x00000008);
        dareacode_ = getDefaultInstance().getDareacode();
        onChanged();
        return this;
      }
      void setDareacode(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000008;
        dareacode_ = value;
        onChanged();
      }
      
      // required string timestamp = 5;
      private java.lang.Object timestamp_ = "";
      public boolean hasTimestamp() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      public String getTimestamp() {
        java.lang.Object ref = timestamp_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          timestamp_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setTimestamp(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        timestamp_ = value;
        onChanged();
        return this;
      }
      public Builder clearTimestamp() {
        bitField0_ = (bitField0_ & ~0x00000010);
        timestamp_ = getDefaultInstance().getTimestamp();
        onChanged();
        return this;
      }
      void setTimestamp(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000010;
        timestamp_ = value;
        onChanged();
      }
      
      // required string type = 6;
      private java.lang.Object type_ = "";
      public boolean hasType() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      public String getType() {
        java.lang.Object ref = type_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          type_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setType(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        type_ = value;
        onChanged();
        return this;
      }
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000020);
        type_ = getDefaultInstance().getType();
        onChanged();
        return this;
      }
      void setType(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000020;
        type_ = value;
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:SmCdr)
    }
    
    static {
      defaultInstance = new SmCdr(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:SmCdr)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_SmCdr_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_SmCdr_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\007cdr.pro\"l\n\005SmCdr\022\r\n\005oaddr\030\001 \002(\t\022\021\n\toar" +
      "eacode\030\002 \002(\t\022\r\n\005daddr\030\003 \002(\t\022\021\n\tdareacode" +
      "\030\004 \002(\t\022\021\n\ttimestamp\030\005 \002(\t\022\014\n\004type\030\006 \002(\t"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_SmCdr_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_SmCdr_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_SmCdr_descriptor,
              new java.lang.String[] { "Oaddr", "Oareacode", "Daddr", "Dareacode", "Timestamp", "Type", },
              CdrPro.SmCdr.class,
              CdrPro.SmCdr.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
